Starting device monitor script
2025-01-19 21:23:19,646 - INFO - Initializing device monitor
2025-01-19 21:23:20,446 - INFO - Successfully imported requests
2025-01-19 21:23:20,447 - INFO - Creating DeviceMonitor instance
2025-01-19 21:23:20,447 - INFO - Initializing DeviceMonitor class
2025-01-19 21:23:20,448 - INFO - Content directory: /var/www/kiosk
2025-01-19 21:23:20,448 - INFO - API URL: https://vinculo.com.py/new-player/api
2025-01-19 21:23:20,448 - INFO - Device ID: device_20250119_06395bce
2025-01-19 21:23:20,448 - INFO - Starting monitor
2025-01-19 21:23:20,449 - INFO - Starting main loop
2025-01-19 21:23:20,465 - INFO - System info collected: {'disk_total': '15G', 'disk_used': '5.7G', 'disk_percent': '43%'}
2025-01-19 21:23:20,465 - INFO - Sending ping to https://vinculo.com.py/new-player/api/ping.php
2025-01-19 21:23:20,466 - DEBUG - Headers: {'X-API-Key': 'w8oMou6uUiUQBE4fvoPamvdKjOwSCNBK', 'X-Device-Id': 'device_20250119_06395bce'}
2025-01-19 21:23:20,466 - DEBUG - Data: {'device_id': 'device_20250119_06395bce', 'timestamp': '2025-01-19T21:23:20.449370', 'system_info': {'disk_total': '15G', 'disk_used': '5.7G', 'disk_percent': '43%'}}
2025-01-19 21:23:20,517 - DEBUG - Starting new HTTPS connection (1): vinculo.com.py:443
2025-01-19 21:23:21,607 - DEBUG - https://vinculo.com.py:443 "POST /new-player/api/ping.php HTTP/1.1" 406 226
2025-01-19 21:23:21,615 - INFO - Response status code: 406
2025-01-19 21:23:21,618 - INFO - Response text: <head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.</p></body></html>
2025-01-19 21:23:21,618 - ERROR - Network error sending ping: 406 Client Error: Not Acceptable for url: https://vinculo.com.py/new-player/api/ping.php
2025-01-19 21:23:21,619 - INFO - Ping result: False
2025-01-19 21:24:21,624 - INFO - System info collected: {'disk_total': '15G', 'disk_used': '5.7G', 'disk_percent': '43%'}
2025-01-19 21:24:21,624 - INFO - Sending ping to https://vinculo.com.py/new-player/api/ping.php
2025-01-19 21:24:21,624 - DEBUG - Headers: {'X-API-Key': 'w8oMou6uUiUQBE4fvoPamvdKjOwSCNBK', 'X-Device-Id': 'device_20250119_06395bce'}
2025-01-19 21:24:21,625 - DEBUG - Data: {'device_id': 'device_20250119_06395bce', 'timestamp': '2025-01-19T21:24:21.619473', 'system_info': {'disk_total': '15G', 'disk_used': '5.7G', 'disk_percent': '43%'}}
2025-01-19 21:24:21,630 - DEBUG - Starting new HTTPS connection (1): vinculo.com.py:443
2025-01-19 21:24:22,621 - DEBUG - https://vinculo.com.py:443 "POST /new-player/api/ping.php HTTP/1.1" 406 226
2025-01-19 21:24:22,632 - INFO - Response status code: 406
2025-01-19 21:24:22,636 - INFO - Response text: <head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.</p></body></html>
2025-01-19 21:24:22,637 - ERROR - Network error sending ping: 406 Client Error: Not Acceptable for url: https://vinculo.com.py/new-player/api/ping.php
2025-01-19 21:24:22,638 - INFO - Ping result: False
